# config.yaml

root_dir: '../hpde.io'
output_dir: './ODIS_JSONLD'
sitemap_file: './sitemap.xml'
base_url: "https://raw.githubusercontent.com/lechatpito/SPASE-to-schemaorg-converter/main/"
datatypes:
  - DisplayData
  - NumericalData
skip_patterns:
  - deprecated
mapping_spec:
  - mapping/mapping_spec.yaml
log_level: ERROR


